### ISSUE TITLE
What is this organization all about ?

### ISSUE THREAD

**Issue by mrtrkmn** [Technojam/First-pr-membership-#1]
Hello Dear Developers,

- I have questions to ask you, what is the purpose of this organization and goals ? 

- In addition to that, how do you invite people ? (according to which criteria ?)

- For instance, why did you invite me and how did you find me ?

**Comment by adeen-s** [comment]
+1 

I have the same questions. Why was I added to this organization?

**Comment by mrtrkmn** [comment]
I think, they do not care very much,  best thing to do is leave off the relationship.
